### ISSUE TITLE
Install docs doesn't work

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden-services#252] opened 2019-04-10 13:47 UTC
Following the instructions here https://raiden-services.readthedocs.io/en/latest/#installation for installation doesn't work. I talked to @Dominik1999 and according to him I need to install latest Raiden Version in my venv first. This should be reflected in the docs.

**Comment by palango** [comment] 2019-04-16 06:55
Do you have a more detailed error message? I guess that the `git` dependencies don't get installed by the `pip install -e .` call.

**Comment by palango** [comment] 2019-04-16 08:32
When trying it out I got. I vaguely remember that this was fixed in raiden recently.
```
Collecting psycopg2>=2.6 (from matrix-synapse==0.33.9->raiden->raiden-services==0.0.1)
  Downloading https://files.pythonhosted.org/packages/23/7e/93c325482c328619870b6cd09370f6dbe1148283daca65115cd63642e60f/psycopg2-2.8.2.tar.gz (368kB)
    100% |████████████████████████████████| 368kB 14.9MB/s
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).


    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/g4/rq2cz9m969x4zy_9x04bdv9r0000gn/T/pip-install-yica8q3t/psycopg2/
```

**Comment by palango** [comment] 2019-04-16 08:45
@ulope Seems like this get pulled in from raiden, but there it is only a dev dependency. Do we actually need this for the (limited) transport we use in the services?

**Comment by ulope** [comment] 2019-04-16 09:01
The problem is that in setup.py install_requires the raiden git url gets replaced with the package name raiden.

We fixed the dependencies in raiden last week to no longer include dev deps when just installing the package, but there is so far no released version that contains this fix.

**Comment by palango** [comment] 2019-04-16 09:02
Makes sense. So we have to wait for the release to include your fix until this works. Thanks!

**Closed** 2019-04-16 09:26 UTC
Labels: Docs :book:, Infrastructure :office:
