### ISSUE TITLE
Suggested hubs always seems to be offline

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/raiden-services#895] opened 2020-12-14 14:34 UTC
In the recent implemented suggested hubs list raiden-network/light-client#2429 , the suggested hubs appear to alway be offline.

## Steps to Reproduce
1. Serve the raiden-network/light-client#2429 PR locally.
2. Select the `0x59105441977ecD9d805A4f5b060E34676F50F806` token
3. Choose any of the suggested hubs

## Expected Result
- For selected hub to appear as online

## Actual Result
- Suggested hub (any of the selected) always appears as offline

## Additional Infos (Optional) 
<img width="658" alt="Screenshot 2020-12-14 at 15 26 23" src="https://user-images.githubusercontent.com/43838780/102093678-b9fadb00-3e21-11eb-8e64-1f6f98868a13.png">

**Comment by karlb** [comment] 2021-01-04 13:56
You can get the suggested nodes without the LC with `curl -X GET https://pfs-goerli.services-dev.raiden.network/api/v1/0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3/suggest_partner`. I'll assume this is caused by https://github.com/raiden-network/raiden/issues/6724 until proved otherwise.

**Comment by karlb** [comment] 2021-02-05 09:24
I assume this has been fixed with raiden-network/raiden#6724. Please reopen if it hasn't.

**Closed by karlb** 2021-02-05 09:24 UTC
Labels: Bug :bug:, Matrix :cyclone:, PFS :rocket:
