### ISSUE TITLE
High gas value on claimReward transaction

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden-services#772] opened 2020-04-23 14:22 UTC
[This transaction](https://etherscan.io/tx/0x577ca5e2b47a15a68a41700e092d0e0c437f0ac8b165424f82c69186efc24e09) has a very high gas value of 9,989,881 although only 45,023 is necessary, according to our `gas.json`.

https://web3py.readthedocs.io/en/stable/web3.eth.html:

> If the transaction specifies a data value but does not specify gas then the gas value will be populated using the estimateGas() function with an additional buffer of 100000 gas up to the gasLimit of the latest block. In the event that the value returned by estimateGas() method is greater than the gasLimit a ValueError will be raised.

So the transactions gas should only be 45,023 + 100,000 = 145,023. But according to etherscan “Max Txn Cost/Fee: 0.09989881 Ether” at 10 Gwei gas price, which is 9,989,881, according to my calculation. This gas value is suspiciously close to the block gas limit, so it probably relates in some way to that value.

**Comment by karlb** [comment] 2020-04-24 09:59
On görli, these transactions usually had a gas value of ~175,058 see https://goerli.etherscan.io/tx/0x8dd56807bf7ac3581bbd4decdc59b49f46008af6ef5193d6a00033f8be3525e4 .

**Comment by hackaugusto** [comment] 2020-04-30 14:10
Note: according to @karlb this was using geth for the gas estimation

**Comment by hackaugusto** [comment] 2020-04-30 14:26
possible approaches to figure out the problem:

- check if web3 is using the block gas limit as a fallback for start gas when something goes wrong.
- estimate gas by hand (this would require re-doing the deposits), the idea here is to check if we can reproduce the problem

**Comment by palango** [comment] 2020-05-04 13:56
These values are calculated by pyEVM in our end-to-end tests:

### monitor

This one looks reasonably close:

estimate:  214131
with buffer:  314131
gas.json: 211668



### claim
For claim however the value seems off by a factor of 2. This doesn't explain the problem, but is surprising.

estimate:  92371
with buffer:  192371
gas.json: 45023

**Comment by palango** [comment] 2020-05-04 15:27
> check if web3 is using the block gas limit as a fallback for start gas when something goes wrong.

Not as far as I can tell: If `gas` is not set for a transaction, it filled by `get_buffered_gas_estimate`:

https://github.com/ethereum/web3.py/blob/05bbf57b97f9c21918f29555b5582ce095674622/web3/_utils/transactions.py#L121-L137

**Comment by palango** [comment] 2020-05-05 12:28
Couldn't reproduce, let's see if this happens again while running the scenarios.

**Comment by Dominik1999** [comment] 2020-05-06 14:15
closing since not reproducible

**Closed by Dominik1999** 2020-05-06 14:15 UTC
Labels: State / Investigating, [SP 34]
