### ISSUE TITLE
Problem in fee calculation

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#637] opened 2019-11-19 13:54 UTC
## Problem Definition

Might be related to #636 

While running the BF1 scenario transfers fail for some people. In the PFS one can see logs messages about failed fee calculations:

```
[36mpfs-goerli-with-fee_1         |[0m {"sender": "0x772340feEB3ED7B93F15bd5F874b2604667C508a", "expected_amount": 200, "total_amount": 200, "added_amount": 100, "event": "Received service fee", "level": "info", "logger": "pathfinding_service.api", "timestamp": "2019-11-19 10:18:33.880731"}
[36mpfs-goerli-with-fee_1         |[0m {"source": "0x772340feEB3ED7B93F15bd5F874b2604667C508a", "target": "0x1c801c278562049d56D64B784E883E843A87fC40", "value": 1000000000000000, "max_paths": 5, "diversity_penalty": 5, "fee_penalty": 100, "reachabilities": {"0xEDC5f296a70096EB49f55681237437cbd249217A": "<AddressReachability.REACHABLE: 1>", "0xF1F4517228F68B95c49a314B02352D9062bD0AC9": "<AddressReachability.UNREACHABLE: 2>", "0x0738dEE4B991Fd183FC7C96ef7F48Cd20d323c9A": "<AddressReachability.UNREACHABLE: 2>", "0xB62b755177F4521C9a75B6eFbd821741cF31e505": "<AddressReachability.UNREACHABLE: 2>", "0x0bB692C69Ba87339DE2c28583C5617b5d841ba4D": "<AddressReachability.UNREACHABLE: 2>", "0xC58FD7F94E068Ea459d7B7CE3e19dD561ed4bC6F": "<AddressReachability.UNREACHABLE: 2>", "0x5a9B5038A391eE187ad626e896FcFfd04Dcd05df": "<AddressReachability.UNREACHABLE: 2>", "0x24F6Ce6f9EC663B9Bf2A50De29f4DAa5281B52e0": "<AddressReachability.UNREACHABLE: 2>", "0x887420A40E63978AF4aA99d503E5455EC4212954": "<AddressReachability.UNREACHABLE: 2>", "0x0d782a2c46CD973Fc5c64cBC0bD1c0D55cd5c6A2": "<AddressReachability.UNREACHABLE: 2>", "0xDE4111084c92d51B5D10e358192fF28e1095563f": "<AddressReachability.UNREACHABLE: 2>", "0x843AF32cb93c116794358D4Fe1b258eB823b3610": "<AddressReachability.UNREACHABLE: 2>", "0xAF43d32ACDcF95e1669eC87388176B6e113f11C4": "<AddressReachability.UNREACHABLE: 2>", "0x4286Fdef66291b79FAE7bc584030A6d8b0d88Da2": "<AddressReachability.UNREACHABLE: 2>", "0x92E677C9a3c0bdC15018a3bd624B5C15E11b5039": "<AddressReachability.UNREACHABLE: 2>", "0xFBcbDe064F864d410b95ed32F14CBc18B5C25503": "<AddressReachability.UNREACHABLE: 2>", "0xaD52b3f719B89FE96EcAa6eACCa815271e03F448": "<AddressReachability.UNREACHABLE: 2>", "0xC0eCe875827f0EDe7C580151f51E185aF6071DEB": "<AddressReachability.UNREACHABLE: 2>", "0x40DAC4c0ACF673bCA08bEC73E1FB79FF1da3778b": "<AddressReachability.UNREACHABLE: 2>", "0x3B955762d81462e99B1544C04e06E99C1f501411": "<AddressReachability.UNREACHABLE: 2>", "0x9135B05B54A4Ca405D90c096Da56C02e34758e5d": "<AddressReachability.UNREACHABLE: 2>", "0xcc4C85C5589b52d2d137c4b34a7c68899D68D173": "<AddressReachability.UNREACHABLE: 2>", "0x8c630F1F34C649A086724269966CD418FD3d8Fa6": "<AddressReachability.UNREACHABLE: 2>", "0x628FC3b8F1B7F7b98F4583FA4f88f99B59C90e9C": "<AddressReachability.UNREACHABLE: 2>", "0xe3C891b8f496CA23804809c9B30cAd183CF7979A": "<AddressReachability.UNREACHABLE: 2>", "0x491f3f3057b3f709Aec10eC232c301E4b1E17792": "<AddressReachability.UNREACHABLE: 2>", "0x477ebFA4BC0ce497D83F158B6913494637cB5E3C": "<AddressReachability.UNREACHABLE: 2>", "0xbD4C98c9eF014bA0a84Edc5968148183576BDC04": "<AddressReachability.UNREACHABLE: 2>", "0xAE0EcfD980E73b524a68727C97F4f83A109ff1bE": "<AddressReachability.UNREACHABLE: 2>", "0xf27Be119Dba775FE1bea200826267993cF44488A": "<AddressReachability.UNREACHABLE: 2>", "0xF38b390F086D024e903b124874902b8863F96a66": "<AddressReachability.UNREACHABLE: 2>", "0x05CEadA241ead5f6773E463e2Da072eb0D833F07": "<AddressReachability.UNREACHABLE: 2>", "0xB0986076F95F93B85Ede0dEbc1a5140d5C06b630": "<AddressReachability.UNREACHABLE: 2>", "0x84eaCA37bDE10744fc5536D942BB9EA6A743ca82": "<AddressReachability.UNREACHABLE: 2>", "0x71e99B2f3452A066Faf140EE8775dD2eF01Dd815": "<AddressReachability.UNREACHABLE: 2>", "0x32005a81e4562f2e33FBbA93A15053ccA89db62c": "<AddressReachability.UNREACHABLE: 2>", "0xaa9d3F868B6ADC6887065A0B46d17b9492B5b5Ad": "<AddressReachability.UNREACHABLE: 2>", "0x954d55f87fdcCa9B985E6201D249E80886f6cbF9": "<AddressReachability.UNREACHABLE: 2>", "0x0150F93ceF7fb401Cb3F1263EA9437B082f88349": "<AddressReachability.UNREACHABLE: 2>", "0x14581e3649a8BE6a3dcE0627da4d80E3844fFd23": "<AddressReachability.UNREACHABLE: 2>", "0x5D7038ddBc14ccb61dBf75663ba296164576D3d5": "<AddressReachability.UNREACHABLE: 2>", "0xEc9Ba001Ca6Fe083E3Bbc3d5E275398f9D01FF85": "<AddressReachability.UNREACHABLE: 2>", "0x4Df6fbaffb0b83Ba33f70f8dFD904885E45b46AD": "<AddressReachability.UNREACHABLE: 2>", "0x854A89E48C4B869bf8C116358cC342d03e8511e1": "<AddressReachability.UNREACHABLE: 2>", "0x8318b46e7ef30F1bdAcBc154D4Ac569EAAd0eAd2": "<AddressReachability.UNREACHABLE: 2>", "0xd3B36509BD6A8023508a7e1063A92b758EecFDF6": "<AddressReachability.UNREACHABLE: 2>", "0xB6BbD91e76b158dF3f4406A209687eF4A854BF69": "<AddressReachability.UNREACHABLE: 2>", "0x398D4cf5732918F6E6445c43b015BF0856FAfD76": "<AddressReachability.UNREACHABLE: 2>", "0x80845D92aCaaeE1f7fFc932046902D1eace1A460": "<AddressReachability.UNREACHABLE: 2>", "0x3f3e780E56c4dDc0Acc71Cf15E75057cA20f01c6": "<AddressReachability.UNREACHABLE: 2>", "0xfD834Beb732bA61d6d217667b2810C00D1b5c7DE": "<AddressReachability.UNREACHABLE: 2>", "0xa306B3Dc9c3B7EbFBf9ff1CAAB9d6dF7EA9Bef4F": "<AddressReachability.UNREACHABLE: 2>", "0x49C706A7B7a982B426A2677de5c35a28a95975bE": "<AddressReachability.UNREACHABLE: 2>", "0x1CF7Ec21EeDf5641C2718f5572901125316eA537": "<AddressReachability.UNREACHABLE: 2>", "0x4A3b84c464B19EfC903CE9d11B5d3e0f4382f70C": "<AddressReachability.UNREACHABLE: 2>", "0xF3A6717e1d574fa014605F2Ff4D38def8aAf6C31": "<AddressReachability.UNREACHABLE: 2>", "0xC7b13e862E2C94e90e32f37a7fb3c0e0aB2e947E": "<AddressReachability.UNREACHABLE: 2>", "0x0185827513619Ad25Cd67cc7beE31410B90346C2": "<AddressReachability.UNREACHABLE: 2>", "0xCd50dbe43E2595457e1662f8854e1F8223B758f0": "<AddressReachability.UNREACHABLE: 2>", "0xe2FB2263EE9037a6795501f77417440AE6b30635": "<AddressReachability.UNREACHABLE: 2>", "0x21C3F50f4859F8258518D455F05666748A4a0C31": "<AddressReachability.UNREACHABLE: 2>", "0xfB30611111d766899e1944747Ae5C2dEe9cEb1AA": "<AddressReachability.UNREACHABLE: 2>", "0x0F9739BCEa99f1f97e9d16B80b4F6a4f20fC72aA": "<AddressReachability.UNREACHABLE: 2>", "0xBf4C2c7922746F7c76FFB1072E9B8582a2E2a887": "<AddressReachability.UNREACHABLE: 2>", "0x4b4fDa62e8e2b4A8209c5E65d534eCC35CB73313": "<AddressReachability.UNREACHABLE: 2>", "0xC2b0c0DA739B5913f7253B52564d9D031F5fFF5b": "<AddressReachability.UNREACHABLE: 2>", "0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6": "<AddressReachability.REACHABLE: 1>", "0xf9907ad11Bf99aa2B522DD70c07D2c172278E0Df": "<AddressReachability.UNREACHABLE: 2>", "0x1Eae79900d99C24F1e3FE746a117917A01ae598F": "<AddressReachability.UNREACHABLE: 2>", "0x557A80B132dB2F8C2B006bA6E8c782699099Ad81": "<AddressReachability.UNREACHABLE: 2>", "0x6eEF8224a9EF5B984E886c9Dd9c17297FD2C004f": "<AddressReachability.UNREACHABLE: 2>", "0x82b2f1fA5E736d430CBf4f4f90eD23F5d27e9a2B": "<AddressReachability.UNREACHABLE: 2>", "0x552e878d97FC12B89bAd8132276944B875671f0f": "<AddressReachability.UNREACHABLE: 2>", "0xeF7BF77eF2FbB896Df5b3042c8E70053206b37Ad": "<AddressReachability.UNREACHABLE: 2>", "0x0294b1C94e2b3C8c763742984816f72D80aF936E": "<AddressReachability.UNREACHABLE: 2>", "0x3438756AE84CE4da74146De272BE70bEA6275474": "<AddressReachability.UNREACHABLE: 2>", "0xbF170824bAa21196128fFc6aedbaf2Fa75223530": "<AddressReachability.UNREACHABLE: 2>", "0x9577DE8b52a0240D9A790125765219b8Aa38762e": "<AddressReachability.UNREACHABLE: 2>", "0x479DCA0D318995169333978c57E545904596430C": "<AddressReachability.UNREACHABLE: 2>", "0xD0F15d5B2FcbB3Eec217020CF738d363D25Fa701": "<AddressReachability.UNREACHABLE: 2>", "0x02731Baa8Df229BFd072EB8CBed761bd7BaCA879": "<AddressReachability.UNREACHABLE: 2>", "0xEDBdb49E2DA55b620B24f2c1C8CeB234117ccD77": "<AddressReachability.UNREACHABLE: 2>", "0x2cF7E06Ecc17357428cd6f62bFcb392cc0c3d338": "<AddressReachability.UNREACHABLE: 2>", "0x20d91f5E20fBA1FF1f90d5aB6a1A9fed24fe0D9B": "<AddressReachability.UNREACHABLE: 2>", "0xc80129e258425e5e8C525c34E0E53b9cf76761CF": "<AddressReachability.UNREACHABLE: 2>", "0x8b3179b0F0853D75146dbA37cc7505cB2DC2A64B": "<AddressReachability.UNREACHABLE: 2>", "0x8fD5F402213DE3A4234ca52a04283eEf4b763b07": "<AddressReachability.UNREACHABLE: 2>", "0x8A12830ad755Ca2ca0ca9cf492022903c221eADa": "<AddressReachability.UNREACHABLE: 2>", "0x6b0a33d58D0d730482Bfc4db4f44da24E8241136": "<AddressReachability.UNREACHABLE: 2>", "0x87524F63e554Bbf7F28655BB38a4882583346F05": "<AddressReachability.UNREACHABLE: 2>", "0xb711d91DFBe01bd94F926106a3733BE00AF29E76": "<AddressReachability.UNREACHABLE: 2>", "0x1267FA7cC325C2090C03Fa77ecCBaBDc1fdAFa85": "<AddressReachability.UNREACHABLE: 2>", "0xa1f97295497a2e32BFaC5b156DD583D453519BE0": "<AddressReachability.UNREACHABLE: 2>", "0x8De80fDA6748135F0054AF5Ad3ae9D1D2cAfDdc1": "<AddressReachability.UNREACHABLE: 2>", "0xff23e2E4aD2ecA89825F0Ee49aB564fC488833B8": "<AddressReachability.UNREACHABLE: 2>", "0x8321F3fB2FC35774a4f0b5cC0bf835435e62F2eE": "<AddressReachability.UNREACHABLE: 2>", "0xc61E9e0424067786e92e2841c3fc98f259951765": "<AddressReachability.UNREACHABLE: 2>", "0x538b1708e395C3B2269F88adC1Da13D672AA40c8": "<AddressReachability.UNREACHABLE: 2>", "0x07ab040CA2C212738b37f009d688b65448A05bd5": "<AddressReachability.UNREACHABLE: 2>", "0x27953A874FcDEdCbCbf6f09F816D313e91F2Df5F": "<AddressReachability.REACHABLE: 1>", "0xDa484E23F2367C161143be7c4418e46427481cB2": "<AddressReachability.UNREACHABLE: 2>", "0xfCD86594D6C2Cc8DCe97F367cd327f2b6b1dfF0A": "<AddressReachability.UNREACHABLE: 2>", "0x05a82FA2dbBbf46f9723c6C5Ca9b4d8AdD554613": "<AddressReachability.UNREACHABLE: 2>", "0x0179091292f7997C091c9bc98D83C4fE336d6e43": "<AddressReachability.UNREACHABLE: 2>", "0x43B91aAFB8868237930d83a005e9a9d9f7dA4E79": "<AddressReachability.UNREACHABLE: 2>", "0x648c10B2d2f744f1B64799d58cec28038a286646": "<AddressReachability.UNREACHABLE: 2>", "0x3E20A34923183fbE7945aB39CC06E8652107c0a3": "<AddressReachability.UNREACHABLE: 2>", "0x0d46BCBeC3539d8A47b59beE1fF9c09E3a2b0D25": "<AddressReachability.UNREACHABLE: 2>", "0xBb75731D94b8556084E356087DE687baaA4389A7": "<AddressReachability.UNREACHABLE: 2>", "0xD1D35F593d2254fFF0fa8cFE5B80E13302d33B5e": "<AddressReachability.UNREACHABLE: 2>", "0x9602c8DCdB43fAe18309AF498A2Bc8460e334A89": "<AddressReachability.REACHABLE: 1>", "0x6678947a9aB1163f3745AA5c321C3522c060Ce23": "<AddressReachability.REACHABLE: 1>", "0x318170050f1d2854961B58875A1f3237822adC8C": "<AddressReachability.REACHABLE: 1>", "0x8A27E755CF849B3dAb9062B4A6b31824cb807651": "<AddressReachability.REACHABLE: 1>", "0x70a5fe4ddc453ddDb8e71Cb43A914Fc7389DA0d4": "<AddressReachability.REACHABLE: 1>", "0x78b2c7e50B1Bb3625037b94AB2011074fA5E9e69": "<AddressReachability.REACHABLE: 1>", "0x86dFfeB0f8b9253b6F3d509b1810E3564768B28A": "<AddressReachability.REACHABLE: 1>", "0x61e8519091a107c88Eed9FE38d3549b6BeE216B6": "<AddressReachability.REACHABLE: 1>", "0xdA8A7051F157f7EcFd8A25589cC65f4f10E7fC33": "<AddressReachability.REACHABLE: 1>", "0xB86Afa537BF5D6F50e6C15E380723de00534ABc1": "<AddressReachability.REACHABLE: 1>", "0x0448143691978E3919e72BfcEF87588235F7FC4e": "<AddressReachability.REACHABLE: 1>", "0x772340feEB3ED7B93F15bd5F874b2604667C508a": "<AddressReachability.REACHABLE: 1>", "0x0163db088e22f1E7C72d67d38fc73De5c935851F": "<AddressReachability.REACHABLE: 1>", "0x1c801c278562049d56D64B784E883E843A87fC40": "<AddressReachability.REACHABLE: 1>", "0x3626Ae109d1B477656105b821D60062c2d2a7676": "<AddressReachability.REACHABLE: 1>", "0x14be0397787764A76Cc42CC980d965442b0893D9": "<AddressReachability.REACHABLE: 1>", "0xA25b6Bb033A9712698c037d6E357e01C829049E0": "<AddressReachability.REACHABLE: 1>", "0x2fAC81a40a63f82F1E7042B2650c6e08DeCD6B51": "<AddressReachability.REACHABLE: 1>", "0xadE14e3C7609434684b4769369397513B3bD6D24": "<AddressReachability.REACHABLE: 1>", "0x937d2De8dE33E761259e4F2E95C474f0Ce4e3B3d": "<AddressReachability.REACHABLE: 1>", "0xF8c53c1F9F9BB2a05f64a68ED391DC1ceEea8edE": "<AddressReachability.REACHABLE: 1>", "0x203eAF7Feef91C00F5d9F56F883aCFe034374327": "<AddressReachability.REACHABLE: 1>", "0x35E2a42a9319018C05Dd8D4A77A01e3227DeA49d": "<AddressReachability.REACHABLE: 1>", "0x76BD6dE21a154fa8194ACf205e5cB74a4E268e8A": "<AddressReachability.REACHABLE: 1>", "0x8fbCF623Db1CcE4dEeAA9A8DE931133ed1D1cEEd": "<AddressReachability.REACHABLE: 1>", "0xD361315597d84181e10145dEBaC159C814237B84": "<AddressReachability.REACHABLE: 1>", "0x0c6Cef33c2E8E1A512C6291dCDD2824130be7EF6": "<AddressReachability.REACHABLE: 1>", "0xe31Eb213675362687e56ca367D2Ab6EaE1032313": "<AddressReachability.REACHABLE: 1>", "0x91DFbAC74F3e90ca62CAa3541941350f9707838B": "<AddressReachability.REACHABLE: 1>", "0x802EDd2Ad3E8c595E51B180EbFB8fA5d9da9057a": "<AddressReachability.REACHABLE: 1>"}, "event": "Finding paths for payment", "level": "debug", "logger": "pathfinding_service.model.token_network", "timestamp": "2019-11-19 10:18:33.903629"}
[36mpfs-goerli-with-fee_1         |[0m {"amount": 1000000000000000, "view_out": "<ChannelView cid=2501 from=0x0163db088e22f1E7C72d67d38fc73De5c935851F to=0x1c801c278562049d56D64B784E883E843A87fC40 capacity=0>", "view_in": "<ChannelView cid=2498 from=0x772340feEB3ED7B93F15bd5F874b2604667C508a to=0x0163db088e22f1E7C72d67d38fc73De5c935851F capacity=0>", "amount_without_fees": 1000000000000000, "balance_in": 1000000000000000000, "balance_out": 0, "schedule_in": "FeeSchedule(cap_fees=True, flat=0, proportional=0, imbalance_penalty=None, timestamp=datetime.datetime(2019, 11, 19, 10, 8, 57, 947405))", "schedule_out": "FeeSchedule(cap_fees=True, flat=0, proportional=0, imbalance_penalty=None, timestamp=datetime.datetime(2019, 11, 19, 10, 11, 55, 858631))", "receivable_amount": 0, "event": "Invalid fee calculation", "level": "warning", "logger": "pathfinding_service.model.token_network", "timestamp": "2019-11-19 10:18:33.936401"}
[36mpfs-goerli-with-fee_1         |[0m {"nodes": ["0x772340feEB3ED7B93F15bd5F874b2604667C508a", "0x0163db088e22f1E7C72d67d38fc73De5c935851F", "0x1c801c278562049d56D64B784E883E843A87fC40"], "value": 1000000000000000, "event": "Checking path validity", "level": "debug", "logger": "pathfinding_service.model.token_network", "timestamp": "2019-11-19 10:18:33.940112"}
[36mpfs-goerli-with-fee_1         |[0m {"nodes": ["0x772340feEB3ED7B93F15bd5F874b2604667C508a", "0x0163db088e22f1E7C72d67d38fc73De5c935851F", "0x1c801c278562049d56D64B784E883E843A87fC40"], "is_valid": false, "fees": [], "event": "Creating Path object", "level": "debug", "logger": "pathfinding_service.model.token_network", "timestamp": "2019-11-19 10:18:33.941005"}
[36mpfs-goerli-with-fee_1         |[0m {"nodes": ["0x772340feEB3ED7B93F15bd5F874b2604667C508a", "0x0163db088e22f1E7C72d67d38fc73De5c935851F", "0x1c801c278562049d56D64B784E883E843A87fC40"], "value": 1000000000000000, "event": "Checking path validity", "level": "debug", "logger": "pathfinding_service.model.token_network", "timestamp": "2019-11-19 10:18:33.948414"}
[36mpfs-goerli-with-fee_1         |[0m {"amount": 1000000000000000, "view_out": "<ChannelView cid=2499 from=0x3626Ae109d1B477656105b821D60062c2d2a7676 to=0x1c801c278562049d56D64B784E883E843A87fC40 capacity=0>", "view_in": "<ChannelView cid=2500 from=0x0448143691978E3919e72BfcEF87588235F7FC4e to=0x3626Ae109d1B477656105b821D60062c2d2a7676 capacity=1000000000000000000>", "amount_without_fees": 1000000000000000, "balance_in": 1000000000000000000, "balance_out": 0, "schedule_in": "FeeSchedule(cap_fees=True, flat=0, proportional=0, imbalance_penalty=None, timestamp=datetime.datetime(2019, 11, 19, 10, 15, 10, 297439))", "schedule_out": "FeeSchedule(cap_fees=True, flat=0, proportional=0, imbalance_penalty=None, timestamp=datetime.datetime(2019, 11, 19, 10, 15, 10, 302725))", "receivable_amount": 1000000000000000000, "event": "Invalid fee calculation", "level": "warning", "logger": "pathfinding_service.model.token_network", "timestamp": "2019-11-19 10:18:33.949786"}
[36mpfs-goerli-with-fee_1         |[0m {"nodes": ["0x772340feEB3ED7B93F15bd5F874b2604667C508a", "0x0448143691978E3919e72BfcEF87588235F7FC4e", "0x3626Ae109d1B477656105b821D60062c2d2a7676", "0x1c801c278562049d56D64B784E883E843A87fC40"], "value": 1000000000000000, "event": "Checking path validity", "level": "debug", "logger": "pathfinding_service.model.token_network", "timestamp": "2019-11-19 10:18:33.952013"}
[36mpfs-goerli-with-fee_1         |[0m {"nodes": ["0x772340feEB3ED7B93F15bd5F874b2604667C508a", "0x0448143691978E3919e72BfcEF87588235F7FC4e", "0x3626Ae109d1B477656105b821D60062c2d2a7676", "0x1c801c278562049d56D64B784E883E843A87fC40"], "is_valid": false, "fees": [], "event": "Creating Path object", "level": "debug", "logger": "pathfinding_service.model.token_network", "timestamp": "2019-11-19 10:18:33.952991"}
[36mpfs-goerli-with-fee_1         |[0m {"nodes": ["0x772340feEB3ED7B93F15bd5F874b2604667C508a", "0x0448143691978E3919e72BfcEF87588235F7FC4e", "0x3626Ae109d1B477656105b821D60062c2d2a7676", "0x1c801c278562049d56D64B784E883E843A87fC40"], "value": 1000000000000000, "event": "Checking path validity", "level": "debug", "logger": "pathfinding_service.model.token_network", "timestamp": "2019-11-19 10:18:33.954890"}
[36mpfs-goerli-with-fee_1         |[0m {"source": "0x772340feEB3ED7B93F15bd5F874b2604667C508a", "target": "0x1c801c278562049d56D64B784E883E843A87fC40", "value": 1000000000000000, "max_paths": 5, "diversity_penalty": 5, "fee_penalty": 100, "paths": [], "event": "Returning paths for payment", "level": "info", "logger": "pathfinding_service.model.token_network", "timestamp": "2019-11-19 10:18:33.956165"}
[36mpfs-goerli-with-fee_1         |[0m {"error": "NoRouteFound(None)", "details": {"from_": "0x772340feEB3ED7B93F15bd5F874b2604667C508a", "to": "0x1c801c278562049d56D64B784E883E843A87fC40", "value": 1000000000000000}, "message": "No route between nodes found.", "event": "Error while handling request", "level": "warning", "logger": "pathfinding_service.api", "timestamp": "2019-11-19 10:18:33.958057"}
[36mpfs-goerli-with-fee_1         |[0m 172.21.0.14 - - [2019-11-19 10:18:33] "POST /api/v1/0xDa1fBc048f503635950058953f5c60FC1F564ee6/paths HTTP/1.1" 404 473 0.171265
```

Used nodes:
```
{"balances": {"0x0448143691978E3919e72BfcEF87588235F7FC4e": 0, "0x0163db088e22f1E7C72d67d38fc73De5c935851F": 0, "0x3626Ae109d1B477656105b821D60062c2d2a7676": 0, "0x772340feEB3ED7B93F15bd5F874b2604667C508a": 0, "0x1c801c278562049d56D64B784E883E843A87fC40": 0}}
```

## Actual Outcome

Fee calculation fails.

## Expected Outcome

Fee calculation shouldn't fail, especially as fees are set to 0 in that scenario.

**Comment by palango** [comment] 2019-11-19 14:09
Another log file:

[dump3.log](https://github.com/raiden-network/raiden-services/files/3864134/dump3.log)

Used addresses:
```
- "node": 0, "address": "0x802EDd2Ad3E8c595E51B180EbFB8fA5d9da9057a"
- "node": 1, "address": "0xe31Eb213675362687e56ca367D2Ab6EaE1032313"
- "node": 2, "address": "0x91DFbAC74F3e90ca62CAa3541941350f9707838B"
- "node": 3, "address": "0x0c6Cef33c2E8E1A512C6291dCDD2824130be7EF6"
- "node": 4, "address": "0xD361315597d84181e10145dEBaC159C814237B84"

**Comment by Dominik1999** [comment] 2019-11-19 14:29
sure, thanks for creating this issue @palango 
Sorry for the big files. Unfortunately, I left the nodes running for a while


[node_24_000.zip](https://github.com/raiden-network/raiden-services/files/3864243/node_24_000.zip)
[node_24_001.zip](https://github.com/raiden-network/raiden-services/files/3864244/node_24_001.zip)
[node_24_002.zip](https://github.com/raiden-network/raiden-services/files/3864245/node_24_002.zip)
[node_24_003.zip](https://github.com/raiden-network/raiden-services/files/3864246/node_24_003.zip)
[node_24_004.zip](https://github.com/raiden-network/raiden-services/files/3864247/node_24_004.zip)

**Comment by karlb** [comment] 2019-11-20 09:28
Here's a more readable version of the first warning:
```python
{
  "amount": 1000000000000000,  # 1e15
  "view_out": "<ChannelView cid=2501 from=0x0163db088e22f1E7C72d67d38fc73De5c935851F to=0x1c801c278562049d56D64B784E883E843A87fC40 capacity=0>",
  "view_in": "<ChannelView cid=2498 from=0x772340feEB3ED7B93F15bd5F874b2604667C508a to=0x0163db088e22f1E7C72d67d38fc73De5c935851F capacity=0>",
  "amount_without_fees": 1000000000000000,  # 1e15
  "balance_in": 1e+18,
  "balance_out": 0,
  "schedule_in": "FeeSchedule(cap_fees=True, flat=0, proportional=0, imbalance_penalty=None, timestamp=datetime.datetime(2019, 11, 19, 10, 8, 57, 947405))",
  "schedule_out": "FeeSchedule(cap_fees=True, flat=0, proportional=0, imbalance_penalty=None, timestamp=datetime.datetime(2019, 11, 19, 10, 11, 55, 858631))",
  "receivable_amount": 0,
  "event": "Invalid fee calculation",
  "level": "warning",
  "logger": "pathfinding_service.model.token_network",
  "timestamp": "2019-11-19 10:18:33.936401"
}
```
The `"receivable_amount": 0` must make this fail, since there is no way to make this payment when the mediator can't receive any tokens on the channel. Maybe that's an expected part of the scenario. I'll have to take a look at where the scenario fails. Does anyone have a scenario log with a failure?

**Comment by Dominik1999** [comment] 2019-11-20 09:38
[scenario-player-run_bf1_basic_functionality_2019-11-19T11:14:16.log](https://github.com/raiden-network/raiden-services/files/3868414/scenario-player-run_bf1_basic_functionality_2019-11-19T11.14.16.log)

**Comment by karlb** [comment] 2019-11-20 09:46
From @Dominik1999's log, the bf1 scenario fails in the "Make 10 payments from 0 to 3 after restart" step.

**Comment by karlb** [comment] 2019-11-20 10:38
The scenario just successfully passed that step for me, so it's not trivially reproducible.

**Comment by karlb** [comment] 2019-11-20 12:22
After two successes, I managed to get a failing bf1 in the step "Make 10 transfers from 3 to 0" at 2019-11-20 11:34:45.540308 with `Payment couldn't be completed because: there is no route available`.

**Comment by karlb** [comment] 2019-11-20 13:08
https://github.com/raiden-network/raiden-services/issues/639 might be a duplicate and has PFS logs attached.

**Comment by karlb** [comment] 2019-11-22 09:53
Duplicate of https://github.com/raiden-network/raiden-services/issues/639.

**Closed by karlb** 2019-11-22 09:53 UTC
Labels: PFS :rocket:, Severity / Medium, Type / Bug
